{{- if .Values.enableNetworkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "genai-arcade.fullname" . }}-api
  labels:
    {{- include "genai-arcade.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "genai-arcade.selectorLabelsApi" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector: {}
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - port: api
          protocol: TCP
  egress:
    - ports:
        - port: redis
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "genai-arcade.selectorLabelsRedis" . | nindent 14 }}
{{- end }}
