---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssh.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SSH_USERS
              value: {{ include "ssh.userDetails" . }}
            - name: SSH_ENABLE_PASSWORD_AUTH
              value: {{ .Values.enablePassword_auth | default "false" | quote }}
            - name: SSH_ENABLE_ROOT_PASSWORD_AUTH
              value: {{ .Values.enableRootPasswordAuth | default "false" | quote }}
            - name: MOTD
              value: {{ .Values.motd | default "" | quote }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: authorized-keys
              mountPath: /etc/authorized_keys/{{ .Values.user.name }}
              subPath: authorized_keys
              readOnly: true
            - name: data
              mountPath: /data
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
      volumes:
        - name: authorized-keys
          configMap:
            name: authorized-keys
            defaultMode: 0444
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim }}
