---
repos:
  - repo: local
    hooks:
      - id: helm-schema
        name: Helm values schema json
        entry: bash -c 'cd stable/component-based-app && helm schema'
        language: system
        pass_filenames: false
        files: ^stable/component-based-app/
        require_serial: true
  - repo: local
    hooks:
      - id: helm-unittest
        name: Helm unit tests
        entry: bash -c 'for d in $(find stable -name Chart.yaml -exec dirname {} \;); do helm unittest "$d" || exit 1; done'
        language: system
        pass_filenames: false
        files: ^stable/
        require_serial: true
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        entry: scripts/helm-docs.sh
        language: system
        pass_filenames: false
        files: ^stable/
        require_serial: true