---
repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: helm-schema
        name: Helm values schema json
        entry: bash -c 'cd stable/component-based-app && helm-values-schema-json'
        language: golang
        additional_dependencies:
          - github.com/losisin/helm-values-schema-json/v2@v2.4.0
        pass_filenames: false
        files: ^stable/component-based-app/
        require_serial: true
  - repo: local
    hooks:
      - id: values-sync
        name: Values files in sync
        entry: scripts/check-values-sync.py
        language: system
        pass_filenames: false
        files: ^stable/
        require_serial: true
      - id: helm-unittest
        name: Helm unit tests
        entry: helmunittest/helm-unittest:3.20.2-1.0.3
        args:
          - stable/static-website
          - stable/component-based-app
        language: docker_image
        pass_filenames: false
        files: ^stable/
        require_serial: true
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        entry: scripts/helm-docs.sh
        language: golang
        additional_dependencies:
          - github.com/norwoodj/helm-docs/cmd/helm-docs@v1.14.2
        pass_filenames: false
        files: ^stable/
        require_serial: true

