apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandpiper.fullnameApi" . }}
  labels:
    {{- include "sandpiper.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
    {{- include "sandpiper.selectorLabels" . | nindent 4 }}
