apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collator.fullnameWeb" . }}
  labels:
    {{- include "collator.labelsWeb" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount | default 1}}
  selector:
    matchLabels:
      {{- include "collator.selectorLabelsWeb" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := merge .Values.commonPodAnnotations .Values.web.podAnnotations }}
      {{- with $annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "collator.labelsWeb" . | nindent 8 }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.web.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "collator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | default .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.web.securityContext | default .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
          {{- if .Values.rabbitmq.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rabbitmq.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- with .Values.web.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.web.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
