apiVersion: v1
kind: Service
metadata:
  name: {{ include "collator.fullnameWeb" . }}
  labels:
    {{- include "collator.labelsWeb" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "collator.selectorLabelsWeb" . | nindent 4 }}
