replicaCount: 1

web:
  image:
    repository: 112652377709.dkr.ecr.ap-southeast-2.amazonaws.com/sandpiper/web
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 8000
    annotations: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraContainers: []
  extraVolumes: []
api:
  image:
    repository: 112652377709.dkr.ecr.ap-southeast-2.amazonaws.com/sandpiper/api
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 5000
    annotations: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraContainers: []
  extraVolumes: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  annotations: {}
  storageClassName: ""
  size: "100Gi"
