apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collator.fullnameApi" . }}
  labels:
    {{- include "collator.labelsApi" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "collator.selectorLabelsApi" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := merge .Values.commonPodAnnotations .Values.api.podAnnotations }}
      {{- with $annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "collator.labelsApi" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "collator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | default .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | default .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: {{ include "collator.fullnameRabbitmq" . }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.service.port | quote }}
          ports:
            - name: api
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- if .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
