apiVersion: v1
kind: Service
metadata:
  name: {{ include "collator.fullnameApi" . }}
  labels:
    {{- include "collator.labelsApi" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "collator.selectorLabelsApi" . | nindent 4 }}
