apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandpiper.fullnameWeb" . }}
  labels:
    {{- include "sandpiper.labels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: web
    {{- include "sandpiper.selectorLabels" . | nindent 4 }}
