apiVersion: v2
name: component-based-app
description: >
  Generic library chart for a research application deployment.
type: application
version: 0.3.0
appVersion: ""
kubeVersion: ">=1.34.7"
icon: ""
sources:
  - https://github.com/eresearchqut/charts
maintainers:
  - name: eResearch QUT
    email: eresearch@qut.edu.au
annotations:
  category: Research
dependencies:
  - name: cluster
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
    alias: database
    condition: database.enabled
