# Default values for the chart
# For usage view values.example.yaml, which also generates the documentation.
# This is the source of truth for the defaults.

global: {}

imagePullSecrets: []

resources: {}

components: {}

ingress:
  annotations: {}
  paths: []

database:
  image:
    repository: registry.eres.qut.edu.au/ghcr/cloudnative-pg/postgresql
  storageSize: 8Gi
  walStorageSize: 2Gi
  instances: 1
  resources:
    requests:
      cpu: "0.5"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  extraEgress: []

networkPolicy:
  allowPublicIngress: false
  monitoringSelector:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring
  cnpgOperatorSelector:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: cnpg-system

serviceAccount:
  enabled: false
  annotations: {}
  automount: false

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

imageUpdate:
  enabled: false
  imageTagPattern: "^(?P<ts>[0-9]+)$"
  imageUpdateBranch: main
  updatePath: "."
  messageTemplate: |
    Automated image update

    Automation name: {{ .AutomationObject }}

    Files:
    {{ range $filename, $_ := .Changed.FileChanges -}}
    - {{ $filename }}
    {{ end -}}

    Objects:
    {{ range $resource, $changes := .Changed.Objects -}}
    - {{ $resource.Kind }} {{ $resource.Name }}
      Changes:
    {{- range $_, $change := $changes }}
        - {{ $change.OldValue }} -> {{ $change.NewValue }}
    {{ end -}}
    {{ end -}}
