---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genai-arcade.fullname" . }}-init-script
  labels:
    {{- include "genai-arcade.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  init.sh: |
    #!/bin/bash
    pip install -U huggingface_hub[cli] &&
    hf download shuyuej/Llama-3.2-3B-Instruct-GPTQ &&
    hf download stable-diffusion-v1-5/stable-diffusion-v1-5
