---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genai-arcade.fullname" . }}-init-script
  labels:
    {{- include "genai-arcade.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  init.sh: |
    {{- .Values.initScript | nindent 4 }}
