{{- range $name, $spec := .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "component-based-app.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/component: {{ $name }}
    {{- include "component-based-app.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "component-based-app.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $spec.port }}
      targetPort: http
{{- end }}
